name: Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: $NODE_VERSION

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test

    - name: App dry run
      run: npm run test:dry-run
